      
projects: {}

applications: 

  openshift-config:
    annotations:
      argocd.argoproj.io/sync-wave: '16'      
    source:
      path: clusters/etl6/overlays/openshift-config

  # nfd-operator:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '5'
  #   source:
  #     path: components/nfd-operator

  # nfd-configuration:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '15'
  #   source:
  #     path: components/nfd-configuration

# Networking

  nmstate-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: clusters/etl6/overlays/nmstate-configuration

  metallb-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: metallb-system
    source:
      path: clusters/etl6/overlays/metallb-configuration      

# Storage

  trident-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: netapp-trident
    source:
      path: clusters/etl6/overlays/trident-configuration

  # trident-protect-operator:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '5'
  #   destination:
  #     namespace: trident-protect
  #   source:
  #     path: components/trident-protect-operator

  # trident-protect-configuration:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '15'
  #   destination:
  #     namespace: trident-protect
  #   source:
  #     path: components/trident-protect-configuration        

  # fusion-access-for-san-operator:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '5'
  #   source:
  #     path: components/fusion-access-for-san-operator

  # fusion-access-for-san-configuration:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '15'
  #   destination:
  #     namespace: ibm-spectrum-scale
  #   source:
  #     path: components/fusion-access-for-san-configuration 

  odf-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    source:
      path: components/odf-operator

  odf-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: openshift-storage
    source:
      path: components/odf-configuration       

# VMs 

  vm-tests:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: vm-tests
    source:
      path: clusters/etl6/overlays/vm-tests

  # trilio-vm-tests:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: '15'
  #   destination:
  #     namespace: trilio-vm-tests
  #   source:
  #     path: clusters/etl6/overlays/trilio-vm-tests
  #   extraFields: |
  #     ignoreDifferences:
  #       - group: 'triliovault.trilio.io'
  #         jsonPointers:
  #           - /spec/objectStoreCredentials/credentialSecret/resourceVersion
  #           - /spec/objectStoreCredentials/credentialSecret/uid
  #         kind: Target
  #       - group: 'triliovault.trilio.io'
  #         kind: BackupPlan
  #         jsonPointers:
  #           - /spec/backupConfig/retentionPolicy/resourceVersion
  #           - /spec/backupConfig/retentionPolicy/uid
  #           - /spec/backupConfig/schedulePolicy/fullBackupPolicy/resourceVersion
  #           - /spec/backupConfig/schedulePolicy/fullBackupPolicy/uid
  #           - /spec/backupConfig/schedulePolicy/incrementalBackupPolicy/resourceVersion
  #           - /spec/backupConfig/schedulePolicy/incrementalBackupPolicy/uid
  #           - /spec/backupConfig/target/resourceVersion
  #           - /spec/backupConfig/target/uid
  #           - /spec/continuousRestoreConfig/continuousRestoreInstances/0/continuousRestorePolicy/resourceVersion
  #           - /spec/continuousRestoreConfig/continuousRestoreInstances/0/continuousRestorePolicy/uid                      


  vlan-dhcp:
    annotations:
      argocd.argoproj.io/sync-wave: '24'     
    source:
      path: clusters/etl6/overlays/vlan-dhcp

# percona demo

  percona-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'     
    source:
      path: clusters/etl6/overlays/percona-operator

  percona-instance:
    annotations:
      argocd.argoproj.io/sync-wave: '10'     
    source:
      path: clusters/etl6/overlays/percona-instance
    extraFields: |
      ignoreDifferences:
      - group: apps
        kind: Deployment
        name: quarkus-petclinic
        jsonPointers:
          - /spec/replicas          

# bgp test

  bgp-test:
    annotations:
      argocd.argoproj.io/sync-wave: '7'     
    destination:
      namespace: openshift-frr-k8s
    source:
      path: clusters/etl6/overlays/bgp-test  

# persistent reservation test      

  persistent-reservations:
    annotations:
      argocd.argoproj.io/sync-wave: '25'     
    destination:
      namespace: persistent-reservations
    source:
      path: clusters/etl4/overlays/persistent-reservations

# kubevirt-bmc

  kubevirt-bmc:
    annotations:
      argocd.argoproj.io/sync-wave: '6'     
    destination:
      namespace: kubevirtbmc-system
    source:
      path: clusters/etl6/overlays/kubevirt-bmc

  kubevirt-bmc-cluster:
    annotations:
      argocd.argoproj.io/sync-wave: '25'     
    destination:
      namespace: kubevirt-bmc-cluster
    source:
      path: clusters/etl6/overlays/kubevirt-bmc-cluster
    extraFields: |
      ignoreDifferences:
      - group: kubevirt.io
        kind: VirtualMachine
        jsonPointers:
          - /spec/template/spec/domain/interfaces/0/macAddress
          - /spec/running         