apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: deny-from-192-168-90-4
  annotations:
    k8s.v1.cni.cncf.io/policy-for: multinetworkpolicy-udn-localnet-test/vlan-2901
spec:
  podSelector: 
    matchLabels:
      vm.kubevirt.io/name: fedora-tomato-marlin-51
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 192.168.90.5/32
    - ipBlock:
        cidr: 192.168.91.3/32        
