FROM quay.io/fedora/fedora-bootc:41

# Make sure that the rootfiles package can be installed
RUN mkdir -p /var/roothome /data

#install rpmfusion
RUN dnf install -y \
	https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
	https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

RUN dnf group install -y \
	base-graphical \
	container-management \
	core \
	firefox \
	fonts \
	gnome-desktop \
	guest-desktop-agents \
	hardware-support \
	multimedia \
	networkmanager-submodules \
	printing \
	virtualization \
	workstation-product
  

RUN dnf install -y \
	#bash-completion \
	htop \
	neovim \
	strace \
	tmate \
	tmux \
	vgrep \ 
  sssd \
  sssd-ldap \
  oddjob-mkhomedir

RUN systemctl set-default graphical.target &&\
    authselect select sssd with-mkhomedir --force &&\
    systemctl enable sssd oddjobd

COPY --chmod=600 sssd.conf /etc/sssd/sssd.conf

# See https://fedoraproject.org/wiki/Changes/UnprivilegedUpdatesAtomicDesktops:
#     Avoid annoying popups when logged in.
RUN dnf install -y fedora-release-ostree-desktop

RUN dnf remove -y gnome-initial-setup

# Close once https://gitlab.com/fedora/bootc/base-images/-/issues/28 is merged and released in the base image
RUN rm -rf /var/run && ln -s /run /var/

#COPY config.json /config.json

# Final lint step to prevent easy-to-catch issues at build time
RUN bootc container lint