apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: node-problem-detector
    app.kubernetes.io/name: node-problem-detector
  name: node-problem-detector
  namespace: openshift-workload-availability
spec:
  selector:
    matchLabels:
      app: node-problem-detector
      app.kubernetes.io/instance: node-problem-detector
      app.kubernetes.io/name: node-problem-detector
  template:
    metadata:
      labels:
        app: node-problem-detector
        app.kubernetes.io/instance: node-problem-detector
        app.kubernetes.io/name: node-problem-detector
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - 'exec /node-problem-detector --logtostderr --config.system-log-monitor=/config/kernel-monitor.json  --config.custom-plugin-monitor=/custom-config/ontap-san-test.json --config.custom-plugin-monitor=/custom-config/bond0-test.json --prometheus-address=0.0.0.0
          --prometheus-port=20257 --k8s-exporter-heartbeat-period=5m0s --v=3'
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        #image: registry.k8s.io/node-problem-detector/node-problem-detector:v0.8.19
        image: quay.io/raffaelespazzoli/node-problem-detector:v0.8.21
        imagePullPolicy: IfNotPresent
        name: node-problem-detector
        ports:
        - containerPort: 20257
          name: exporter
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/log/
          name: log
          readOnly: true
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /custom-config
          name: custom-config
          readOnly: true
        - mountPath: /node-root
          name: node-root          
        volumeDevices:
        - name: ontap-san-test
          devicePath: /dev/ontap-san-test
      hostNetwork: true
      hostPID: false
      priorityClassName: system-node-critical
      serviceAccountName: node-problem-detector
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /var/log/
        name: log
      - hostPath:
          path: /
        name: node-root        
      - hostPath:
          path: /etc/localtime
          type: FileOrCreate
        name: localtime
      - configMap:
          defaultMode: 493
          name: node-problem-detector-custom-config
        name: custom-config
      - name: ontap-san-test
        persistentVolumeClaim:
          claimName: ontap-san-test
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate