apiVersion: policies.kyverno.io/v1alpha1
kind: MutatingPolicy
metadata:
  name: taint-node-on-ontap-san-condition
spec:
  autogen:
   mutatingAdmissionPolicy:
    enabled: false
   podControllers:
     controllers: []
  matchConstraints:
    resourceRules:
    - apiGroups: [ "" ]
      apiVersions: [ "v1" ]
      operations: ["CREATE", "UPDATE"]
      resources: [ "nodes" ]
  failurePolicy: Ignore
  reinvocationPolicy: IfNeeded      
  evaluation:
    admission:
      enabled: true
  matchConditions:
    - name: taint-node-on-ontap-san-condition
      expression: "object.status.conditions.filter(condition, condition.type=='OntapSANProblem' && condition.status=='True').size() == 1"
  mutations:    
  - patchType: ApplyConfiguration
    jsonPatch:
      expression: |
        has(object.spec.taints) ?
        [
          JSONPatch{
            op: "add",
            path: "/spec/taints/-",
            value: {
              "key": "OntapSANProblem",
              "value": "true",
              "effect": "NoExecute"
            }
          }
        ] :
        [
          JSONPatch{
            op: "add",
            path: "/spec/taints",
            value: [{
              "key": "OntapSANProblem",
              "value": "true",
              "effect": "NoExecute"
            }]
          }
        ]
---
apiVersion: policies.kyverno.io/v1alpha1
kind: MutatingPolicy
metadata:
  name: taint-node-on-bond0-condition
spec:
  autogen:
   mutatingAdmissionPolicy:
    enabled: false
   podControllers:
     controllers: []
  matchConstraints:
    resourceRules:
    - apiGroups: [ "" ]
      apiVersions: [ "v1" ]
      operations: ["CREATE", "UPDATE"]
      resources: [ "nodes" ]
  failurePolicy: Ignore
  reinvocationPolicy: IfNeeded      
  evaluation:
    admission:
      enabled: true
  matchConditions:
    - name: taint-node-on-bond0-condition
      expression: "object.status.conditions.filter(condition, condition.type=='Bond0Problem' && condition.status=='True').size() == 1"
  mutations:    
  - patchType: ApplyConfiguration
    jsonPatch:
      expression: |
        has(object.spec.taints) ?
        [
          JSONPatch{
            op: "add",
            path: "/spec/taints/-",
            value: {
              "key": "Bond0Problem",
              "value": "true",
              "effect": "NoExecute"
            }
          }
        ] :
        [
          JSONPatch{
            op: "add",
            path: "/spec/taints",
            value: [{
              "key": "Bond0Problem",
              "value": "true",
              "effect": "NoExecute"
            }]
          }
        ]            
# ---
# apiVersion: policies.kyverno.io/v1alpha1
# kind: MutatingPolicy
# metadata:
#   name: tolerate-ontap-san-problem  
# spec:
#   autogen:
#    mutatingAdmissionPolicy:
#     enabled: false
#    podControllers:
#      controllers: []
#   matchConstraints:
#     resourceRules:
#     - apiGroups: [ "" ]
#       apiVersions: [ "v1" ]
#       operations: ["CREATE", "UPDATE"]
#       resources: [ "pods" ]
#   failurePolicy: Ignore
#   reinvocationPolicy: IfNeeded      
#   evaluation:
#     admission:
#       enabled: true
#   matchConditions:
#     - name: no-volumes-with-ontap-san-storage-class
#       expression: "!has(object.spec.volumes) || object.spec.volumes.filter(volume, has(volume.persistentVolumeClaim)).map(volume, resource.Get('v1', 'persistentvolumeclaims', object.metadata.namespace, volume.persistentVolumeClaim.claimName)).filter(pvc, pvc.spec.storageClassName == 'ontap-san').size() == 0"
#   mutations:    
#   - patchType: ApplyConfiguration
#     jsonPatch:
#       expression: |
#         has(object.spec.tolerations) ?
#         [
#           JSONPatch{
#             op: "add",
#             path: "/spec/tolerations/-",
#             value: {
#               key: "OntapSANProblem",
#               value: "true",
#               effect: "NoExecute"
#             }
#           }
#         ] :
#         [
#           JSONPatch{
#             op: "add",
#             path: "/spec/tolerations",
#             value: [{
#               key: "OntapSANProblem",
#               value: "true",
#               effect: "NoExecute"
#             }]
#           }
#         ]
---
apiVersion: policies.kyverno.io/v1alpha1
kind: MutatingPolicy
metadata:
  name: tolerate-bond0-problem
spec:
  autogen:
   mutatingAdmissionPolicy:
    enabled: false
   podControllers:
     controllers: []
  matchConstraints:
    resourceRules:
    - apiGroups: [ "" ]
      apiVersions: [ "v1" ]
      operations: ["CREATE", "UPDATE"]
      resources: [ "pods" ]
  failurePolicy: Ignore
  reinvocationPolicy: IfNeeded      
  evaluation:
    admission:
      enabled: true
  matchConditions:
    - name: no-networks-whose-name-starts-with-vlan
      expression: "!has(object.metadata.annotations) || object.metadata.annotations['k8s.v1.cni.cncf.io/networks'].filter(net, net.name.startsWith('vlan-')).size() == 0"
  mutations:    
  - patchType: ApplyConfiguration
    jsonPatch:
      expression: |
        has(object.spec.tolerations) ?
        [
          JSONPatch{
            op: "add",
            path: "/spec/tolerations/-",
            value: {
              "key": "Bond0Problem",
              "value": "true",
              "effect": "NoExecute"
            }
          }
        ] :
        [
          JSONPatch{
            op: "add",
            path: "/spec/tolerations",
            value: [{
              "key": "Bond0Problem",
              "value": "true",
              "effect": "NoExecute"
            }]
          }
        ]           