apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: secret
spec:
  authentication:
    path: etl7
    role: vault-admin
    serviceAccount:
      name: default
  type: kv
  description: "KV v2 engine for experiment secrets"
  options:
    version: "2"
