apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-monitoring

resources:
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - config-configmap.yaml
  - ca-bundle-configmap.yaml
  - dashboards-configmap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - consolelink.yaml
