apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: sdn-gateway
  namespace: openshift-ingress
spec:
  gatewayClassName: openshift-default
  listeners:
  - name: https
    hostname: "*.gwapi-sdn.${CLUSTER_BASE_DOMAIN}"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - group: ''	
        kind: Secret
        name: gwapi-sdn-tls      
    allowedRoutes:
      namespaces:
        from: All