agent_address = "/run/spire/sockets/agent.sock"
daemon_mode = true

cert_dir = "/var/run/secrets/spiffe"
svid_file_name = "svid.crt.pem"
svid_key_file_name = "svid.key.pem"
svid_bundle_file_name = "bundle.crt.pem"

jwt_svids = [
  {
    jwt_audience      = "vault"
    jwt_svid_file_name = "jwt-svid.token"
  }
]

cert_file_mode = 0640
key_file_mode = 0640
jwt_svid_file_mode = 0640
