
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-masters-multipath-reservation-key
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,ZGVmYXVsdHMgewogICAgcmVzZXJ2YXRpb25fa2V5IGZpbGUKfQo=
          filesystem: root
          mode: 420
          path: /etc/multipath/conf.d/reservation.conf
---

apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-workers-multipath-reservation-key
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,ZGVmYXVsdHMgewogICAgcmVzZXJ2YXRpb25fa2V5IGZpbGUKfQo=
          filesystem: root
          mode: 420
          path: /etc/multipath/conf.d/reservation.conf          