apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: rhcl-operator
  namespace: open-cluster-management-policies
spec:
  upgradeApproval: Automatic
  complianceConfig:
    catalogSourceUnhealthy: Compliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  complianceType: musthave
  remediationAction: enforce
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Keep
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  severity: medium
  subscription:
    channel: stable
    name: rhcl-operator
    namespace: kuadrant-system
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: rhcl-operator.v1.1.0
  versions: 
    - rhcl-operator.v1.1.0
    - rhcl-operator.v1.1.1
    - rhcl-operator.v1.2.0