apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zero-trust-workload-identity-manager

resources:
  - zero-trust-workload-identity-manager.yaml
  - spire-server.yaml
  - spire-agent.yaml
  - spiffe-csi-driver.yaml
  - spire-oidc-discovery-provider.yaml
