apiVersion: operator.openshift.io/v1alpha1
kind: SpireServer
metadata:
  name: cluster
spec:
  logLevel: "info"
  logFormat: "text"
  jwtIssuer: "PLACEHOLDER"
  caValidity: "24h"
  defaultX509Validity: "1h"
  defaultJWTValidity: "5m"
  caKeyType: "rsa-2048"
  jwtKeyType: "rsa-2048"
  caSubject:
    country: "US"
    organization: "Red Hat Labs"
    commonName: "SPIRE Server CA"
  persistence:
    size: "1Gi"
    accessMode: "ReadWriteOnce"
    storageClass: "PLACEHOLDER"
  datastore:
    databaseType: "sqlite3"
    connectionString: "/run/spire/data/datastore.sqlite3"
    maxOpenConns: 100
    maxIdleConns: 10
    connMaxLifetime: 0
    disableMigration: "false"
