apiVersion: operator.openshift.io/v1alpha1
kind: SpireServer
metadata:
  name: cluster
spec:
  logLevel: "info"
  logFormat: "text"
  jwtIssuer: "https://oidc-discovery.apps.${CLUSTER_BASE_DOMAIN}"
  caValidity: "24h"
  defaultX509Validity: "1h"
  defaultJWTValidity: "5m"
  caKeyType: "rsa-2048"
  jwtKeyType: "rsa-2048"
  upstreamAuthority:
    certManager:
      namespace: zero-trust-workload-identity-manager
      issuerName: spire-root-ca-issuer
      issuerKind: ClusterIssuer
      issuerGroup: cert-manager.io
  caSubject:
    country: "US"
    organization: "Red Hat Labs"
    commonName: "SPIRE Server CA"
  persistence:
    size: "1Gi"
    accessMode: "ReadWriteOnce"
    storageClass: "ontap-nas"
  datastore:
    databaseType: "sqlite3"
    connectionString: "/run/spire/data/datastore.sqlite3"
    maxOpenConns: 100
    maxIdleConns: 10
    connMaxLifetime: 0
    disableMigration: "false"
