apiVersion: operator.openshift.io/v1alpha1
kind: ZeroTrustWorkloadIdentityManager
metadata:
  name: cluster
spec:
  trustDomain: "${CLUSTER_BASE_DOMAIN}"
  clusterName: "${CLUSTER_NAME}"
  bundleConfigMap: "spire-bundle"
