apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: argocd-agent-cluster-secrets-policy
  namespace: acm-policies
spec:
  remediationAction: enforce
  disabled: false
  hubTemplateOptions:
    serviceAccountName: policy-admin
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: argocd-agent-cluster-secrets-policy
        spec:
          remediationAction: enforce
          severity: low
          object-templates-raw: |-
            {{- range $mc := (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "").items }}
            {{- if and (index $mc.metadata.labels "gitops") (eq (index $mc.metadata.labels "gitops") "deploy") }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: cluster-argocd-agent-{{ $mc.metadata.name }}
                  namespace: argocd-agent-principal
                  labels:
                    argocd.argoproj.io/secret-type: cluster
                    argocd-agent.argoproj-labs.io/agent-name: argocd-agent-{{ $mc.metadata.name }}
                  annotations:
                    argocd.argoproj.io/skip-reconcile: "true"
                type: Opaque
                stringData:
                  name: argocd-agent-{{ $mc.metadata.name }}
                  server: "https://argocd-agent-principal-agent-principal-resource-proxy:9090?agentName=argocd-agent-{{ $mc.metadata.name }}"
            {{- end }}
            {{- end }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: argocd-agent-cluster-secrets-placement
  namespace: acm-policies
spec:
  clusterSets:
  - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            local-cluster: "true"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: argocd-agent-cluster-secrets-binding
  namespace: acm-policies
subjects:
  - kind: Policy
    apiGroup: policy.open-cluster-management.io
    name: argocd-agent-cluster-secrets-policy
placementRef:
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
  name: argocd-agent-cluster-secrets-placement
