apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-agent-principal-cert
  namespace: argocd-agent-principal
spec:
  secretName: argocd-agent-principal-tls
  commonName: argocd-agent-principal
  issuerRef:
    name: argocd-agent-ca-issuer
    kind: Issuer
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - argocd-agent-principal-agent-principal-argocd-agent-principal.apps.${HUB_BASE_DOMAIN}
    - argocd-agent-principal-agent-principal.argocd-agent-principal.svc
    - argocd-agent-principal-agent-principal.argocd-agent-principal.svc.cluster.local
  usages:
    - server auth
