apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: coraza-waf
  labels:
    istio.io/rev: istio-yellow  
spec:
  imagePullPolicy: IfNotPresent
  phase: AUTHN
  pluginConfig:
    default_directives: default
    directives_map:
      default:
      - Include @demo-conf
      - SecDebugLogLevel 9
      - SecRuleEngine On
      - Include @crs-setup-conf
      - Include @owasp_crs/*.conf
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: yellow-gateway
  url: oci://ghcr.io/corazawaf/coraza-proxy-wasm