apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: yellow-gateway
  namespace: istio-system-yellow
spec:
  gatewayClassName: openshift-default
  listeners:
  - name: https
    hostname: "*.gwapi-yellow.vips.${CLUSTER_BASE_DOMAIN}"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - group: ''	
        kind: Secret
        name: gateway-ingress-certs-tls      
    allowedRoutes:
      namespaces:
        from: All