apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: yellow-gateway
  namespace: istio-system-yellow
  labels:
    istio.io/rev: istio-yellow
spec:
  gatewayClassName: istio
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: '*.gwapi-yellow.vips.${CLUSTER_BASE_DOMAIN}'    
  listeners:
  - name: https
    hostname: "*.gwapi-yellow.vips.${CLUSTER_BASE_DOMAIN}"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - group: ''	
        kind: Secret
        name: gateway-ingress-certs-tls      
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            istio-discovery: yellow