---
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: istio-yellow
spec:
  version: v1.28.1
  namespace: istio-system-yellow
  profile: openshift
  updateStrategy:
    type: InPlace
    inactiveRevisionDeletionGracePeriodSeconds: 30
  values:
    pilot:
      cni:
        enabled: false
      enabled: true    
      env:
        PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER: 'true'
      #   ENABLE_GATEWAY_API_MANUAL_DEPLOYMENT: 'false'
      #   PILOT_MULTI_NETWORK_DISCOVER_GATEWAY_API: 'false'
      #   PILOT_ENABLE_GATEWAY_API_STATUS: 'true'
      #   PILOT_GATEWAY_API_CONTROLLER_NAME: openshift.io/gateway-controller/v1
      #   PILOT_ENABLE_ALPHA_GATEWAY_API: 'false'
      #   PILOT_ENABLE_GATEWAY_API: 'true'
      #   PILOT_GATEWAY_API_DEFAULT_GATEWAYCLASS_NAME: openshift-default
      #   PILOT_ENABLE_GATEWAY_API_GATEWAYCLASS_CONTROLLER: 'false'
      #   PILOT_ENABLE_GATEWAY_API_COPY_LABELS_ANNOTATIONS: 'false'
      #   PILOT_ENABLE_GATEWAY_API_CA_CERT_ONLY: 'true'      
      image: quay.io/sridhargaddam/pilot:ovnk-udn-1.28
      podAnnotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
        k8s.ovn.org/open-default-ports: |
          - protocol: tcp
            port: 15017
          - protocol: tcp
            port: 15012
          - protocol: tcp
            port: 8080
          - protocol: tcp
            port: 15010
          - protocol: tcp
            port: 15014            
    global:
      imagePullPolicy: "Always"
      defaultPodDisruptionBudget:
        enabled: false
      istioNamespace: istio-system-yellow
      priorityClassName: system-cluster-critical      
    meshConfig:
      accessLogFile: /dev/stdout
      discoverySelectors:
        - matchLabels:
            istio-discovery: yellow
      defaultConfig:
        proxyHeaders:
          envoyDebugHeaders:
            disabled: true
          metadataExchangeHeaders:
            mode: IN_MESH
          server:
            disabled: true
      ingressControllerMode: 'OFF'
    sidecarInjectorWebhook:
      enableNamespacesByDefault: false            
                       