apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: cudn-yellow
spec:     
  namespaceSelector:
    matchLabels:
      istio-discovery: yellow
  network:
    topology: Layer2
    layer2:
      role: Primary
      ipam:
        mode: Enabled
        lifecycle: Persistent
      subnets:
        - 22.233.0.0/16                             