apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-br1-multiple-networks 
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: '' 
  desiredState:
    interfaces:
    - name: ovs-br1 
      description: |-
        A dedicated OVS bridge to all of the VM's VLANs
      type: ovs-bridge
      state: up
      ipv4:
        enabled: false 
      ipv6:
        enabled: false      
      bridge:
        allow-extra-patch-ports: true
        options:
          stp: 
            enabled: false
        port:
        - name: bond0
    ovn:
      bridge-mappings:
      - localnet: vlan-2522 
        bridge: ovs-br1 
        state: present
      - localnet: vlan-2901 
        bridge: ovs-br1 
        state: present
      - localnet: vlan-2911 
        bridge: ovs-br1 
        state: present        
# ---
# apiVersion: nmstate.io/v1
# kind: NodeNetworkConfigurationPolicy
# metadata:
#   name: infinidat-iscsi-dl380g9-8
# spec:
#   nodeSelector:
#     kubernetes.io/hostname: dl380g9-8.etl7.ocp.rht-labs.com 
#   desiredState:
#     interfaces:
#     - ipv4:
#         dhcp: false
#         enabled: false
#       name: bond0.2911
#       state: absent
#       type: vlan
#       vlan:
#         base-iface: bond0
#         id: 2911
#     - name: linux-br-iscsi
#       description: |-
#         A dedicated bridge for the infinidat iscsi traffic
#       type: linux-bridge
#       state: absent
#       ipv4:
#         enabled: true
#         address:
#           - ip: 192.168.91.8
#             prefix-length: 24 
#       ipv6:
#         enabled: false      
#       bridge:
#         options:
#           stp: 
#             enabled: false
#         port:
#         - name: bond0.2911        
# ---
# apiVersion: nmstate.io/v1
# kind: NodeNetworkConfigurationPolicy
# metadata:
#   name: infinidat-iscsi-dl380g9-9
# spec:
#   nodeSelector:
#     kubernetes.io/hostname: dl380g9-9.etl7.ocp.rht-labs.com 
#   desiredState:
#     interfaces:
#     - ipv4:
#         dhcp: false
#         enabled: false
#       name: bond0.2911
#       state: absent
#       type: vlan
#       vlan:
#         base-iface: bond0
#         id: 2911
#     - name: linux-br-iscsi
#       description: |-
#         A dedicated bridge for the infinidat iscsi traffic
#       type: linux-bridge
#       state: absent
#       ipv4:
#         enabled: true
#         address:
#           - ip: 192.168.91.9
#             prefix-length: 24 
#       ipv6:
#         enabled: false      
#       bridge:
#         options:
#           stp: 
#             enabled: false
#         port:
#         - name: bond0.2911
# ---
# apiVersion: nmstate.io/v1
# kind: NodeNetworkConfigurationPolicy
# metadata:
#   name: infinidat-iscsi-dl380g9-10
# spec:
#   nodeSelector:
#     kubernetes.io/hostname: dl380g9-10.etl7.ocp.rht-labs.com 
#   desiredState:
#     interfaces:
#     - ipv4:
#         dhcp: false
#         enabled: false
#       name: bond0.2911
#       state: absent
#       type: vlan
#       vlan:
#         base-iface: bond0
#         id: 2911
#     - name: linux-br-iscsi
#       description: |-
#         A dedicated bridge for the infinidat iscsi traffic
#       type: linux-bridge
#       state: absent
#       ipv4:
#         enabled: true
#         address:
#           - ip: 192.168.91.10
#             prefix-length: 24 
#       ipv6:
#         enabled: false      
#       bridge:
#         options:
#           stp: 
#             enabled: false
#         port:
#         - name: bond0.2911

