apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spire-vault-demo

resources:
  - namespace.yaml
  - cert-bootstrap.yaml
  - virtual-machine.yaml
  - service.yaml
  - route.yaml
  - spire-registration-job.yaml
  - tpm-cert-bootstrap.yaml
  - tpm-virtual-machine.yaml
  - tpm-service.yaml
  - tpm-route.yaml
  - tpm-spire-registration-job.yaml
