apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: spire-vault-demo-tpm-vm
  namespace: spire-vault-demo
  labels:
    app: spire-vault-demo-tpm
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: spire-vault-demo-tpm-vm-rootdisk
      spec:
        source:
          registry:
            url: docker://quay.io/raffaelespazzoli/rhel10-spire-vault-demo-disk:latest
        storage:
          accessModes:
            - ReadWriteMany
          volumeMode: Block
          resources:
            requests:
              storage: 20Gi
          storageClassName: ontap-san
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/os: rhel10
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: spire-vault-demo-tpm-vm
        app: spire-vault-demo-tpm
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            - disk:
                bus: virtio
              name: bootstrap-cert-disk
              serial: TPMBOOTCERT
          interfaces:
            - macAddress: 02:2e:13:d9:31:c5
              masquerade: {}
              name: default
              ports:
                - port: 22
                - port: 8080
          rng: {}
          tpm:
            persistent: true
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.6.0
        memory:
          guest: 4Gi
        resources: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: raffa-key
            propagationMethod:
              noCloud: {}
      volumes:
        - dataVolume:
            name: spire-vault-demo-tpm-vm-rootdisk
          name: rootdisk
        - secret:
            secretName: tpm-devid-bootstrap-cert
          name: bootstrap-cert-disk
        - cloudInitNoCloud:
            userDataSecretRef:
              name: tpm-vm-cloud-init
          name: cloudinitdisk
