apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: percona-demo-glb-entries
spec:
  endpoints:
  - dnsName: percona-demo.glb.${PLATFORM_BASE_DOMAIN}
    recordTTL: 180
    recordType: A
    targets:
    #etl6
    - 10.9.52.144
    #etl7
    #- 10.9.53.39
  - dnsName: petclinic.glb.${PLATFORM_BASE_DOMAIN}
    recordTTL: 180
    recordType: A
    targets:
    #etl6
    - 10.9.52.152
    #etl7
    #- 10.9.53.40  