agent {
    data_dir = "/opt/spire/data"
    log_level = "DEBUG"
    trust_domain = "etl7.ocp.rht-labs.com"
    server_address = "spire-server.apps.etl7.ocp.rht-labs.com"
    server_port = "443"
    socket_path = "/run/spire/sockets/agent.sock"
    insecure_bootstrap = true
}

plugins {
    NodeAttestor "x509pop" {
        plugin_data {
            private_key_path = "/etc/spire/bootstrap/agent.key.pem"
            certificate_path = "/etc/spire/bootstrap/agent.crt.pem"
        }
    }
    KeyManager "disk" {
        plugin_data {
            directory = "/opt/spire/data"
        }
    }
    WorkloadAttestor "unix" {
        plugin_data {}
    }
}
