agent {
    data_dir = "/opt/spire/data"
    log_level = "DEBUG"
    trust_domain = "etl7.ocp.rht-labs.com"
    server_address = "spire-server.apps.etl7.ocp.rht-labs.com"
    server_port = "443"
    socket_path = "/run/spire/sockets/agent.sock"
    insecure_bootstrap = true
}

plugins {
    NodeAttestor "tpm_devid" {
        plugin_data {
            devid_cert_path = "/etc/spire/tpm-devid/devid.crt.pem"
            devid_priv_path = "/etc/spire/tpm-devid/devid.priv.blob"
            devid_pub_path  = "/etc/spire/tpm-devid/devid.pub.blob"
        }
    }
    KeyManager "disk" {
        plugin_data {
            directory = "/opt/spire/data"
        }
    }
    WorkloadAttestor "unix" {
        plugin_data {}
    }
}
