apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/ztwim-instance

patches:
  - target:
      kind: ZeroTrustWorkloadIdentityManager
      group: operator.openshift.io
      version: v1alpha1
    patch: |-
      - op: replace
        path: /spec/trustDomain
        value: 'etl7.ocp.rht-labs.com'
      - op: replace
        path: /spec/clusterName
        value: 'etl7'
  - target:
      kind: SpireServer
      group: operator.openshift.io
      version: v1alpha1
    patch: |-
      - op: replace
        path: /spec/jwtIssuer
        value: 'https://oidc-discovery.apps.${CLUSTER_BASE_DOMAIN}'
      - op: replace
        path: /spec/persistence/storageClass
        value: 'ontap-san'
  - target:
      kind: SpireOIDCDiscoveryProvider
      group: operator.openshift.io
      version: v1alpha1
    patch: |-
      - op: replace
        path: /spec/jwtIssuer
        value: 'https://oidc-discovery.apps.${CLUSTER_BASE_DOMAIN}'
