{{ $dot := . }}
{{ range $index,$element:= until (int .Values.disks) }}
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/allowClaimAdoption: 'true'
    cdi.kubevirt.io/storage.usePopulator: 'true'
  name: fedora-virtio-blk-vm-rose-chicken-{{$index}}
  namespace: vm-tests
  ownerReferences:
    - apiVersion: kubevirt.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: VirtualMachine
      name: fedora-virtio-blk-vm
  labels:
    {{- include "vm-disk-test.labels" $dot | nindent 4 }}
spec:
  source:
    blank: {}
  storage:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
    storageClassName: ontap-nas
    volumeMode: Filesystem
---    
{{ end }}    
