apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    {{- include "vm-disk-test.labels" . | nindent 4 }}
  name: fedora-virtio-blk-vm
  namespace: vm-tests
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: fedora-rose-rhinoceros-68
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
    {{- range $index,$element:= until (int .Values.disks) }}         
    - metadata:
        creationTimestamp: null
        name: fedora-virtio-blk-vm-rose-chicken-{{$index}}
      spec:
        source:
          blank: {}
        storage:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 10Gi
          storageClassName: ontap-nas
          volumeMode: Filesystem
      {{- end }}    
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        kubevirt.io/pci-topology-version: v3
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: fedora-rose-rhinoceros-68
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 6
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            {{- range $index,$element:= until (int .Values.disks) }}
            - disk:
                bus: virtio
              name: disk-rose-chicken-{{$index}}
            {{- end }}  
          interfaces:
            - macAddress: '02:2c:82:51:df:fd'
              masquerade: {}
              model: virtio
              name: default
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
          serial: 9b43702a-a0ac-4605-9f8e-abdac14b84c1
          uuid: 775a5172-95e1-43ba-b4c4-6bec4551f8f9
        machine:
          type: pc-q35-rhel9.6.0
        memory:
          guest: 20Gi
        resources: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: fedora-rose-rhinoceros-68
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: p0e2-u6us-k7o4
              chpasswd: { expire: False }
              ssh_authorized_keys:
                  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCWVnOEYFaN6tp/CXn5aBgD5YZbbwJHhUYbAahoGz3IbP8YZZwyBvJvgy9CujKTaIpZHweYRwMEtvPaX65g8AQDd8t6Gqc+JVJue6HTqrawH2wvq8Qdhip9L09fK2WqtP7UbVF+fgiwm9kebajkAqtlOttcdHipeRy5TGVE2hbV1zqc6UjTo6lKzxflm2Jd5EMc4TZCleSFApBod+jgFZoke/8Q/GHWyQs7YaoE3h/JND7z6aye5HoAPQBT18y/4Amwj7h2hIcIsSJ8JAHsOZ0NB4gz1qwpkG/dYAYV1iARM/+qnZ7EJAt4DofqUAS1/0BdXK+1RL8uI0db4r8U3pTe+oFGORQHRNa+ehDoX1PdOU+o59OmjEaJpcq0YRB3NqOwfZzATUfOqcZswH0xC6WKi/UknBFPgJv6JfD0+dee/kWTmgFrzT6Ie9hRql2bA+qjSoPfWzPk+Gv1Wuf6UGdC2DpKPO+vOhVzRtog/cvwjGSJv5p2X6biRGiYy8a0bX0= rspazzol@rspazzol              
          name: cloudinitdisk
        {{- range $index,$element:= until (int .Values.disks) }}  
        - dataVolume:
            name: fedora-virtio-blk-vm-rose-chicken-{{$index}}
          name: disk-rose-chicken-{{$index}}
        {{- end }}  
