apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: loki 
spec:
  size: 1x.small 
  storage:
    schemas:
    - effectiveDate: '2023-10-15'
      version: v13
    secret:
      name: netobserv-loki-s3 
      type: s3 
      credentialMode: static
  storageClassName: ontap-nas
  tenants:
    mode: openshift-network
    openshift:
      adminGroups: 
      - cluster-admin    
  limits:
    global: 
      retention: 
        days: 1