apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: vlan-2911
spec:     
  namespaceSelector:
    matchLabels:
      vlan-2911: "true"
  network:
    topology: Localnet
    localnet:
      physicalNetworkName: vlans
      role: Secondary
      ipam:
        mode: Disabled
      vlan:
        mode: Access
        access:
           id: 2911
---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: vlan-2901
spec:     
  namespaceSelector:
    matchLabels:
      vlan-2901: "true"
  network:
    topology: Localnet
    localnet:
      physicalNetworkName: vlans
      role: Secondary
      ipam:
        mode: Disabled
      vlan:
        mode: Access
        access:
           id: 2901                                         