apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,ServerSideApply=true  
spec:
  channel: stable-4.20
  desiredUpdate:
    version: 4.20.4
    image: quay.io/openshift-release-dev/ocp-release@sha256:5b87a665045cdfe0a1b271024be936a0c46de17b25a112d6a136c5af89d861c4    