apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,ServerSideApply=true  
spec:
  # additionalRoutingCapabilities:
  #   providers:
  #   - FRR
  defaultNetwork:
    ovnKubernetesConfig:
      routeAdvertisements: Enabled