apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: bgp-app-test
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.access.redhat.com/ubi9/nginx-122
        command: ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
        ports:
        - containerPort: 80