apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  labels:
    use-for-advertisements: "true"
  name: receive-filtered
  namespace: openshift-frr-k8s
spec:
  nodeSelector: {}
  bgp:
    routers:
    - asn: 65001
      neighbors:
      - address: 10.9.49.81
        asn: 65000
        disableMP: true
        toReceive:
          allowed:
            mode: filtered
            prefixes:
            - prefix: 0.0.0.0/0