apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  labels:
    use-for-advertisements: "true"
  name: receive-filtered
  namespace: openshift-frr-k8s
spec:
  nodeSelector: {}
  bgp:
    routers:
    - asn: 65005
      neighbors:
      - address: 192.168.100.2
        asn: 65000
        disableMP: true
        dualStackAddressFamily: false
        toReceive:
          allowed:
            mode: filtered
            prefixes:
            - prefix: 0.0.0.0/0