apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: vm-dr-test
spec:
  action: Relocate
  # action: Failover
  drPolicyRef:
    apiVersion: ramendr.openshift.io/v1alpha1
    kind: DRPolicy
    name: etl6-to-etl7
  kubeObjectProtection:
    captureInterval: 5m0s
    kubeObjectSelector:
      matchExpressions:
        - key: app
          operator: In
          values:
            - fedora-vm1
            - fedora-vm2      
  placementRef:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: vm-dr-test
    namespace: openshift-gitops
  #preferredCluster: etl6
  #failoverCluster: etl7
  preferredCluster: etl7
  failoverCluster: etl6  
  pvcSelector:
    matchLabels:
      app: containerized-data-importer

