apiVersion: operator.openshift.io/v1
kind: KubeDescheduler
metadata:
  name: cluster
spec:
  managementState: Managed
  deschedulingIntervalSeconds: 60
  mode: "Automatic"
  profiles:
    - KubeVirtRelieveAndMigrate
  profileCustomizations:
    devEnableSoftTainter: true
    devDeviationThresholds: AsymmetricLow
    devActualUtilizationProfile: PrometheusCPUMemoryCombinedProfile
  evictionLimits:
    node: 2
    total: 5     