apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acm-policies

resources:
- namespace.yaml
- placement.yaml
- managedclustersetbinding.yaml
- policy-service-account.yaml
- propagate-secret-policy.yaml
- servicemesh-federation-policy.yaml
- kuadrant-coredns-policy.yaml
- percona-root-ca-policy.yaml
- vm-dnsrecord-policy.yaml
- volume-group-replication-class-policy.yaml

generators:
- policy-generator-config.yaml