apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gitops-policy-generator
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
  hubTemplateOptions:
    serviceAccountName: policy-admin
placementBindingDefaults:
  name: "binding-policy-gitops"
policies:
  - name: policy-gitops-subscription
    configurationPolicyAnnotations:
      startingCSV: '{{hub (lookup "policy.open-cluster-management.io/v1beta1" "OperatorPolicy" "open-cluster-management-policies" "openshift-gitops-operator").spec.subscription.startingCSV | default "openshift-gitops-operator.v1.20.4" hub}}'
    remediationAction: enforce
    manifests:
      - path: manifests/gitops-subscription/base/namespace.yaml
      - path: manifests/gitops-subscription/base/operator-policy.yaml
      - path: manifests/gitops-subscription/base/cluster-rolebinding.yaml
  - name: policy-gitops-instance
    # Needed to fix issue with merging lists resulting in duplicates
    configurationPolicyAnnotations:
      apps.open-cluster-management.io/reconcile-option: replace
    complianceType: "mustonlyhave"
    manifests:
      - path: manifests/gitops-instance/base/setenv-cmp-plugin-configmap.yaml
      - path: manifests/gitops-instance/base/argocd.yaml
      - path: manifests/gitops-instance/base/environment-variables-configmap.yaml
  - name: policy-gitops-bootstrap
    manifests:
      - path: manifests/gitops-bootstrap/base/bootstrap-app.yaml
policySets:
  - name: "gitops"
    description: "Policy for bootstrapping cluster with gitops"
    policies:
      - policy-gitops-subscription
      - policy-gitops-instance
      - policy-gitops-bootstrap
    generatePolicySetPlacement: false
    placement:
      name: placement-policy-gitops
