apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: propagate-secret-policy
  # Must be a recognized policy namespace on the hub
  namespace: acm-policies
spec:
  remediationAction: enforce
  disabled: false
  hubTemplateOptions:
    serviceAccountName: policy-admin
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: propagate-secret-policy
        spec:
          remediationAction: enforce
          severity: low
          object-templates-raw: |-
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: fence-agents-remediation.medik8s.io/v1alpha1
                kind: FenceAgentsRemediationTemplate
                metadata:
                  name: main-remediation
                  namespace: openshift-workload-availability
                spec:
                  template:
                    spec:
                      remediationStrategy: OutOfServiceTaint
                      agent: fence_redfish
                      nodeparameters:
                        '--ip':
                        {{hub range (lookup "metal3.io/v1alpha1" "BareMetalHost" .ManagedClusterName "").items hub}}
                          {{hub .metadata.name hub}}: {{hub (split "/" .spec.bmc.address)._2  hub}}
                        {{hub end hub}}
                      retrycount: 5
                      retryinterval: 5s
                      sharedparameters:
                        '--action': reboot #also possible "off"
                        '--ipport': '443'
                        '--password': {{hub (lookup "v1" "Secret" .ManagedClusterName "bmc-credentials").data.password | base64dec hub}}
                        '--ssl-insecure': ''
                        '--username': {{hub (lookup "v1" "Secret" .ManagedClusterName "bmc-credentials").data.username | base64dec hub}}
                      timeout: 1m0s
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: redfish-secret
                  namespace: 'openshift-power-monitoring'
                type: Opaque
                stringData:
                  redfish.csv: |-
                  {{hub- $cluster := .ManagedClusterName hub}}
                  {{hub- range (lookup "metal3.io/v1alpha1" "BareMetalHost" .ManagedClusterName "").items hub}}
                    {{hub .metadata.name hub}},{{hub (lookup "v1" "Secret" $cluster "bmc-credentials").data.username | base64dec hub}},{{hub (lookup "v1" "Secret" $cluster "bmc-credentials").data.password | base64dec hub}},https://{{hub (split "/" .spec.bmc.address)._2  -hub}}
                  {{hub end hub}}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: propagate-secret-placement
  namespace: acm-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            gitops: deploy
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: propagate-secret-binding
  namespace: acm-policies
subjects:
  - kind: Policy
    apiGroup: policy.open-cluster-management.io
    name: propagate-secret-policy
placementRef:
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
  name: placement-policy-gitops