object-templates-raw: |
  {{- if not (lookup "v1" "namespace" "openshift-gitops" "") }}
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          openshift.io/cluster-monitoring: "true"
        name: openshift-gitops
  {{- end }}
  {{- if not (lookup "v1" "namespace" "openshift-gitops-operator" "") }}
  - complianceType: musthave
    objectDefinition:
      apiVersion: v1
      kind: Namespace
      metadata:
        labels:
          openshift.io/cluster-monitoring: "true"
        name: openshift-gitops-operator
  {{- end }}
