apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: scsi3pr-vm1
  labels:
    app: scsi3pr-vm1
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: scsi3pr-vm1
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: scsi3pr-vm1
        kubevirt.io/size: small
        network.kubevirt.io/headlessService: headless
    spec:
      evictionStrategy: LiveMigrateIfPossible
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            - errorPolicy: report
              lun:
                bus: scsi
                reservation: true
              name: prdisk
              shareable: true
          interfaces:
            - macAddress: '02:a5:cf:00:01:01'
              masquerade: {}
              model: virtio
              name: default
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 2Gi
        resources: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: raffa-key
            propagationMethod:
              noCloud: {}
      volumes:
        - dataVolume:
            name: scsi3pr-vm1
          name: rootdisk
        - name: prdisk
          persistentVolumeClaim:
            claimName: pr-volume
        - cloudInitNoCloud:
            secretRef:
              name: scsi3pr-cloudinit
          name: cloudinitdisk
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: scsi3pr-vm2
  labels:
    app: scsi3pr-vm2
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: scsi3pr-vm2
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: scsi3pr-vm2
        kubevirt.io/size: small
        network.kubevirt.io/headlessService: headless
    spec:
      evictionStrategy: LiveMigrateIfPossible
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            - errorPolicy: report
              lun:
                bus: scsi
                reservation: true
              name: prdisk
              shareable: true
          interfaces:
            - macAddress: '02:a5:cf:00:01:02'
              masquerade: {}
              model: virtio
              name: default
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 2Gi
        resources: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      accessCredentials:
        - sshPublicKey:
            source:
              secret:
                secretName: raffa-key
            propagationMethod:
              noCloud: {}
      volumes:
        - dataVolume:
            name: scsi3pr-vm2
          name: rootdisk
        - name: prdisk
          persistentVolumeClaim:
            claimName: pr-volume
        - cloudInitNoCloud:
            secretRef:
              name: scsi3pr-cloudinit
          name: cloudinitdisk
